remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Home
show_excerpts: false # set to true to show excerpts on the homepage


# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - projects.md
 - about.md
theme: jekyll-theme-midnight